export default [{
  en_name: 'football',
  cn_name: '足球',
  show_name: 'football_c',
  sCode: 0,
}, {
  en_name: 'basketball',
  cn_name: '篮球',
  show_name: 'basketball_c',
  sCode: 1,
}, {
  en_name: 'volleyball',
  cn_name: '排球',
  show_name: 'volleyball_c',
  sCode: 2,
}, {
  en_name: 'pingpong',
  cn_name: '乒乓球',
  show_name: 'pingpong_c',
  sCode: 3,
}, {
  en_name: 'badminton',
  cn_name: '羽毛球',
  show_name: 'badminton_c',
  sCode: 4,
}, {
  en_name: 'tennis',
  cn_name: '网球',
  show_name: 'tennis_c',
  sCode: 5,
}]
